" Main Vim configuration entrypoint.
" Files in config/ are loaded alphabetically.

let s:config_dir = expand('<sfile>:p:h') . '/config'

for s:config_file in sort(split(glob(s:config_dir . '/*.vim'), "\n"))
  execute 'source' fnameescape(s:config_file)
endfor

unlet s:config_file
unlet s:config_dir
